//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Primer_Asunto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musics
    {
        public string Titulo { get; set; }
        public string Artista { get; set; }
        public string Genero { get; set; }
        public string Album { get; set; }
        public string Calificación { get; set; }
        public Nullable<System.DateTime> Fecha_Creación { get; set; }
        public System.DateTime Fecha_Agregación { get; set; }
    }
}
